import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import gif from "../public/mint.gif";
import bck from "../public/background.png";
import React, { useEffect, useState } from "react";
// import { AiOutlinePlus, AiOutlineMinus } from "react-icons/ai";

export default function Home() {
  const [mintAmount, setMintAmount] = useState(1);

  const decrementMintAmount = () => {
    let newMintAmount = mintAmount - 1;
    if (newMintAmount < 1) {
      newMintAmount = 1;
    }
    setMintAmount(newMintAmount);
  };

  const incrementMintAmount = () => {
    let newMintAmount = mintAmount + 1;
    if (newMintAmount > 10) {
      newMintAmount = 10;
    }
    setMintAmount(newMintAmount);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h1>AirGoblins</h1>
            <p className={styles.minted}>5000/5000</p>
            {/* <input type="number">{mintAmount}</input> */}
            <div className={styles.amount}>{mintAmount}</div>

            <div className={styles.numbers}>
              <button className={styles.buttons} onClick={incrementMintAmount}>
                +
              </button>

              <button className={styles.buttons} onClick={decrementMintAmount}>
                -
              </button>
            </div>

            <div className={styles.minting}>
              <button className={styles.mint}> Mint</button>
              <span className={styles.desc}>
                First 444 free (3 per wallet), then 0,004 eth (10 per tx)
              </span>
            </div>
          </div>

          <div className={styles.image}>
            <Image
              src={gif}
              alt="Picture of the author"
              width={500}
              height={500} //automatically provided
            />
          </div>
        </div>
      </main>
    </div>
  );
}
